var WEBSITE_CONTENT_WRAPPER = 'content',

    LEFT_PANE_IDENTIFIER = 'leftPane',
    LEFT_PANE_SELECTOR = '#' + LEFT_PANE_IDENTIFIER,
    RIGHT_PANE_IDENTIFIER = 'rightPane',
    RIGHT_PANE_SELECTOR = '#' + RIGHT_PANE_IDENTIFIER,

    QUOTE_BUBBLE_CONTENT_ID = 'quoteContent';